[web]
web1
web2
web3

[db]
db1

[monitoring]
mon1

[all:vars]
ansible_user=devops
ansible_password=devops123
ansible_connection=ssh
ansible_become_password=devops123

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
