[blue]
web1

[green]
web2

[lb]
web3

[db]
db1

[all:vars]
ansible_user=devops
ansible_password=devops123
ansible_connection=ssh
ansible_become_password=devops123
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
