---
- hosts: lb
  become: yes

  tasks:

    - name: Configure nginx
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;

              location / {
                  proxy_pass http://{{ backend_target }};
              }

              location /api/ {
                  proxy_pass http://{{ backend_target }}:3000/;
              }
          }

    - name: Reload nginx
      shell: nginx -s reload
