---
- hosts: lb
  become: yes

  tasks:

    - name: Switch traffic
      replace:
        path: /etc/nginx/sites-available/default
        regexp: 'web[12]:3000'
        replace: '{{ backend_target }}:3000'

    - name: Reload nginx
      shell: nginx -s reload
